import createClient from 'openapi-fetch';
import type {paths} from '../types/api'; // generated by openapi-typescript

export function createRequestInstance(
  baseURL: string
): ReturnType<typeof createClient<paths>> {
  return createClient<paths>({baseUrl: baseURL});
}

export type RequestInstance = ReturnType<typeof createRequestInstance>;

export default createRequestInstance;
